name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
on: workflow_dispatch    

jobs:

  build:
    # use ubuntu for more build minutes
    runs-on: ubuntu-latest
    # use release mode for all steps
    env:
      config: 'Release'                  # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

      # restore dependencies
    - name: Install dependencies
      run: dotnet restore

      # build project
    - name: Build
      run: dotnet build --configuration $config --no-restore

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
